name: wf-docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build docker
        run: |
          docker build -t local/test:${{ github.sha }} .

      - name: List images
        run: docker images