# .github/actions/mi-accion/action.yml
name: "Mi Acción"
description: "Ejemplo simple"

inputs:
  nombre:
    required: true
    description: "Nombre del usuario"

runs:
  using: "composite"
  steps:
    - run: echo "Hola ${{ inputs.nombre }}"
      shell: bash