name: node-lint
description: Run eslint

inputs:
  working-directory:
    required: true
  install-command:
    required: true
  lint-command:
    required: true
  node-version:
    required: true
  npm-token:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: ${{ inputs.install-command }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}

    - name: Run lint
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: ${{ inputs.lint-command }}