# .github/workflows/test.yml
name: Test acción

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ejecutar mi acción
        uses: ./.github/actions/mi-accion
        with:
          nombre: "Juan"